print("hello world")
print("hello world of python", "congrats", " for your first program",sep = "|")
print("apple","banana","cherry", sep="|")
print("A","B","C","E",sep="-")
print("Python","rocks",sep ="-",end="|Always\n")
print("hello world from Python",end="!\n")
print("one ",end = "")
print("two ",end = "")
print("three ",end = "")
print("A","B","C","D","E","F",sep = "*",end ="$\n")
print("F","G","H","I","J","K",sep = "*",end ="$\n")
#Red, Green, Blue...Done!
print("Red","Green","Blue...",sep=",",end="Done!\n")
# Python | 3.12 | Awesome
print("Python "," 3.12 "," Awesome ",sep="|")